language: cpp
compiler:
  - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq astyle
script:
 - cd test && make test
 - astyle -X --style=google -n ../**/*.cc ../include/**/*.h | grep Formatted
 - ../script/formatting_checker.sh
